# Generated by Django 4.0.4 on 2022-04-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('team_leader', models.CharField(blank=True, default=None, max_length=20)),
            ],
        ),
    ]
