# Generated by Django 4.0.4 on 2022-04-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_hourly_rate',
            field=models.FloatField(default=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_team_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management_system.team'),
        ),
    ]
