# Generated by Django 4.0.4 on 2022-04-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0003_employee_emp_hourly_rate_employee_emp_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default=None, max_length=50)),
                ('emp_hourly_rate', models.FloatField(default=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default=None, max_length=50)),
                ('emp_hourly_rate', models.FloatField(default=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='teamleader',
            name='emp_team_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management_system.team'),
        ),
        migrations.AddField(
            model_name='teamemployee',
            name='emp_team_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management_system.team'),
        ),
    ]
