# Generated by Django 4.0.4 on 2022-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0005_alter_teamemployee_emp_team_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamleader',
            name='emp_team_name',
        ),
        migrations.AddField(
            model_name='teamleader',
            name='emp_team_name',
            field=models.ManyToManyField(to='employee_management_system.team'),
        ),
    ]
