# Generated by Django 4.0.4 on 2022-04-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0008_alter_teamleader_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleader',
            name='emp_team_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='employee_management_system.team', unique=True),
        ),
    ]
