# Generated by Django 4.0.4 on 2022-04-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0010_alter_teamleader_emp_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleader',
            name='emp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management_system.teamemployee'),
        ),
    ]
