# Generated by Django 4.0.4 on 2022-04-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0012_workarrangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='workarrangement',
            name='work_time_percentange',
            field=models.IntegerField(choices=[(100, 100), (75, 75), (50, 50), (25, 25)], default=100),
        ),
        migrations.AddField(
            model_name='workarrangement',
            name='work_type',
            field=models.CharField(default='Part-time', editable=False, max_length=15),
        ),
    ]
