# Generated by Django 4.0.4 on 2022-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0014_alter_teamleader_emp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamemployee',
            name='emp_work_arrangement',
            field=models.ManyToManyField(to='employee_management_system.workarrangement'),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='emp_work_arrangement',
            field=models.ManyToManyField(to='employee_management_system.workarrangement'),
        ),
    ]
