# Generated by Django 4.0.4 on 2022-04-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0015_teamemployee_emp_work_arrangement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default=None, max_length=50)),
                ('emp_hourly_rate', models.FloatField(default=15)),
                ('emp_work_arrangement', models.ManyToManyField(to='employee_management_system.workarrangement')),
            ],
        ),
        migrations.RemoveField(
            model_name='teamemployee',
            name='emp_hourly_rate',
        ),
        migrations.RemoveField(
            model_name='teamemployee',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='teamemployee',
            name='emp_team_name',
        ),
        migrations.RemoveField(
            model_name='teamemployee',
            name='emp_work_arrangement',
        ),
        migrations.DeleteModel(
            name='TeamLeader',
        ),
    ]
