# Generated by Django 4.0.4 on 2022-04-23 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0016_employee_remove_teamemployee_emp_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name_m', models.CharField(default=None, max_length=50)),
                ('emp_team_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='employee_management_system.team')),
            ],
        ),
    ]
