# Generated by Django 4.0.4 on 2022-04-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0017_teamleader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamleader',
            name='emp_name_m',
        ),
        migrations.AddField(
            model_name='teamleader',
            name='emp_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='employee_management_system.employee'),
        ),
    ]
