# Generated by Django 4.0.4 on 2022-04-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0019_teamemployee_emp_name_teamemployee_emp_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamemployee',
            name='emp_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='employee_management_system.employee', unique=True),
        ),
        migrations.AlterField(
            model_name='teamemployee',
            name='emp_team_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='employee_management_system.team'),
        ),
    ]
