# Generated by Django 4.0.4 on 2022-04-23 21:54

from django.db import migrations, models
import employee_management_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0020_alter_teamemployee_emp_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_work_arrangement',
            field=models.ManyToManyField(to='employee_management_system.workarrangement', validators=[employee_management_system.models.work_arrangement_validator]),
        ),
    ]
